<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Contains the test cases of luma</description>
   <name>TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2e1776aa-e5de-414d-90ea-b9de75ceee13</testSuiteGuid>
   <testCaseLink>
      <guid>a4984d5c-c3d8-49d1-b9e2-423ae2eeabfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_AddToCart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae054e76-1947-48ef-8628-d237a107be1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb3e9a20-d86a-4936-abf2-958fdd8395c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>966fea60-7d65-41cd-849f-1daf167a5ce8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>084b9421-d588-49ad-9d1f-14cd0200c377</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a287527-5e45-44a9-89ba-a42d0282047d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_SignIn</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9abffa8f-76bf-4598-ab80-77ab1289486d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0c0380f-1bcd-4edd-9132-890379df2fb0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
