name: Run Changed Katalon Test Suites

on:
  push:
    branches: [ main ]

jobs:
  katalon-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Detect Changed Test Suites
      id: detect
      run: |
        git fetch origin main
        $changedSuites = git diff --name-only origin/main HEAD | Select-String "^Test Suites/.*\.ts"
        echo "Changed test suites:"
        echo "$changedSuites"
        echo "changed_suites=$changedSuites" >> $env:GITHUB_ENV

    - name: Run Changed Test Suites
      if: env.changed_suites != ''
      run: |
        foreach ($suite in "${{ env.changed_suites }}".Split("`n")) {
          Write-Host "Running test suite: $suite"
          "C:\Path\To\Your\Katalon\katalon.exe" -noSplash -runMode=console -projectPath="${{ github.workspace }}" `
          -retry=0 -testSuitePath="$suite" -executionProfile="default" -browserType="Chrome"
        }
