name: Katalon Test Execution
 
on:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  katalon-tests:
    runs-on: windows-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: Get changed test suites
        id: changes
        run: |
          echo "CHANGED_SUITES="
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "Test Suites/" | tr '\n' ',' | sed 's/,$//')
          echo "Changed Test Suites: $CHANGED"
          echo "CHANGED_SUITES=$CHANGED" >> $GITHUB_ENV
 
      - name: Run Katalon Studio for changed suites
        if: env.CHANGED_SUITES != ''
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '10.3.2'
          projectPath: 'C:/Users/10835442/git/CICD/CICD.prj'
          args: >
            -noSplash
            -runMode=console
            -projectPath="C:/Users/10835442/git/CICD/CICD.prj"
            -retry=0
            -testSuitePath="${{ env.CHANGED_SUITES }}"
            -executionProfile="default"
            -browserType="Chrome"
            -reportFolder="Reports"
            -reportFileName="TestReport"