name: Run Katalon Test Suites on Changes
 
on:
  push:
    branches: [ master ]
  workflow_dispatch:
 
jobs:
  katalon-test:
    runs-on: windows-latest
 
    steps:
      #  Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
 
      #  Setup Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      #  Detect changed test suites or test cases
      - name: Detect Changed Test Suites or Test Cases
        id: detect
        shell: pwsh
        run: |
          git fetch --unshallow || true
 
          $changedFiles = git diff --name-only HEAD^ HEAD
 
          # Detect changed test suites (.ts) and test cases (.tc)
          $changedSuites = $changedFiles | Where-Object { $_ -like "Test Suites/*.ts" }
          $changedTestCases = $changedFiles | Where-Object { $_ -like "Test Cases/*.tc" }
 
          $affectedSuites = @()
 
          # Add directly changed test suites
          if ($changedSuites) {
            $affectedSuites += $changedSuites
          }
 
          # If test cases changed, find which suites reference them
          if ($changedTestCases) {
            Write-Host "Detecting which test suites include the modified test cases..."
            foreach ($tc in $changedTestCases) {
              $tcName = [System.IO.Path]::GetFileNameWithoutExtension($tc)
              $referencingSuites = Get-ChildItem "Test Suites" -Filter "*.ts" -Recurse | Select-String -Pattern $tcName | ForEach-Object { $_.Path }
              if ($referencingSuites) {
                $affectedSuites += $referencingSuites
              }
            }
          }
 
          # Remove duplicates
          $affectedSuites = $affectedSuites | Sort-Object -Unique
 
          if ($affectedSuites.Count -gt 0) {
            Write-Host "Detected changes in or affecting the following test suites:"
            $affectedSuites | ForEach-Object { Write-Host $_ }
 
            # Remove the .ts extension for Katalon compatibility
            $suitePaths = $affectedSuites | ForEach-Object {
              $_ -replace '\.ts$', ''
            }
 
            # Join multiple suites with semicolon
            $joinedSuites = ($suitePaths -join ";")
 
            echo "CHANGED_SUITES=$joinedSuites" >> $env:GITHUB_ENV
            echo "run_suites=true" >> $env:GITHUB_ENV
          } else {
            Write-Host "No related test suite changes detected."
            echo "run_suites=false" >> $env:GITHUB_ENV
          }
 
      #  Run Changed Test Suites
      - name: Run Changed Test Suites
        if: env.run_suites == 'true'
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '10.3.2'
          projectPath: '${{ github.workspace }}'
          args: >-
            -apiKey=${{ secrets.KATALON_API_KEY }}
            -testSuitePath="${{ env.CHANGED_SUITES }}"
            -executionProfile="default"
            -browserType="Chrome"
            -retry=0
            -noSplash
 
      #  Upload HTML reports
      - name: Upload Katalon Reports
        if: env.run_suites == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: katalon-report
          path: Reports/
 
      #  No changes detected
      - name: No changes detected
        if: env.run_suites == 'false'
        run: echo "No test suite or relevant test case changes detected. Skipping run."
