name: Run Katalon Test Suites on Changes
 
on:
  push:
    branches: [ master ]
 
jobs:
  katalon-test:
    runs-on: windows-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
 
    - name: Detect Changed Files
      id: detect
      shell: pwsh
      run: |
        git fetch --unshallow
        $changedFiles = git diff --name-only HEAD^ HEAD
 
        $testCaseChanged = $changedFiles | Select-String "^Test Cases/.*\.tc"
        $testSuiteChanged = $changedFiles | Select-String "^Test Suites/.*\.ts"
 
        if ($testCaseChanged -or $testSuiteChanged) {
          echo "Detected changes in test cases or test suites."
          echo "run_all_suites=true" >> $env:GITHUB_ENV
        } else {
          echo "No relevant changes detected."
          echo "run_all_suites=false" >> $env:GITHUB_ENV
        }
 
    - name: Run All Test Suites
      if: env.run_all_suites == 'true'
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
        version: '10.3.2'                          # Katalon Studio version
        projectPath: '${{ github.workspace }}'     # Path to your project
        testSuitePath: 'Test Suites'               # You can use folder path to run all suites
        executionProfile: 'default'
        browserType: 'Chrome'
        includeHtmlReport: 'true'
 
    - name: Upload Reports
      if: env.run_all_suites == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: katalon-report
        path: Reports/
 
    - name: No changes detected
      if: env.run_all_suites == 'false'
      run: echo "No test case or test suite changes detected. Skipping run."