name: Run Katalon Test Suites on Changes

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: windows-latest
    outputs:
      suites: ${{ steps.set-matrix.outputs.suites }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Changed Test Suites
        id: set-matrix
        shell: pwsh
        run: |
          git fetch --unshallow
          $changedFiles = git diff --name-only HEAD^ HEAD
          $testSuiteChanged = $changedFiles | Where-Object { $_ -like "Test Suites/*.ts" }

          $suitePaths = @()
          foreach ($suite in $testSuiteChanged) {
            $suitePaths += ($suite -replace '\.ts$', '')
          }

          if ($suitePaths.Count -eq 0) {
            echo "::set-output name=suites::[]"
          } else {
            $json = "[" + ($suitePaths | ForEach-Object { '"' + $_ + '"' }) -join "," + "]"
            echo "::set-output name=suites::$json"
          }

  run-suites:
    needs: detect-changes
    runs-on: windows-latest
    strategy:
      matrix:
        suite: ${{ fromJson(needs.detect-changes.outputs.suites) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Test Suite
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '10.3.2'
          projectPath: '${{ github.workspace }}'
          args: >-
            -apiKey=${{ secrets.KATALON_API_KEY }}
            -testSuitePath="${{ matrix.suite }}"
            -executionProfile="default"
            -browserType="Chrome"
            -retry=0
            -noSplash

      - name: Upload Katalon Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-report-${{ matrix.suite }}
          path: Reports/