name: Katalon CI/CD
 
on:
  push:
    paths:
      - 'Test Suites/**'
      - 'Scripts/**'
      - 'Object Repository/**'
  pull_request:
    paths:
      - 'Test Suites/**'
      - 'Scripts/**'
      - 'Object Repository/**'
 
jobs:
  run-katalon-tests:
    runs-on: windows-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to get all history for detecting changed files
 
      - name: Set up Katalon version
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '10.3.2'
 
      - name: Detect changed test suites
        id: changed-suites
        run: |
          echo "Detecting changed test suites..."
          git fetch --unshallow || true
          # List all changed files in Test Suites folder
          CHANGED_TS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "Test Suites/" | grep "\.ts$")
          if [ -z "$CHANGED_TS" ]; then
            echo "No test suites changed."
            echo "suites=" >> $GITHUB_OUTPUT
          else
            # Convert paths to comma-separated list
            SUITES=$(echo $CHANGED_TS | tr ' ' ',')
            echo "Changed test suites: $SUITES"
            echo "suites=$SUITES" >> $GITHUB_OUTPUT
          fi
 
      - name: Run Katalon changed test suites
        if: steps.changed-suites.outputs.suites != ''
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '10.3.2'
          projectPath: 'D:\a\CICD\CICD\CICD.prj'
          testSuitePath: ${{ steps.changed-suites.outputs.suites }}
          executionProfile: 'default'
          browserType: 'Chrome'
          includeHtmlReport: true