name: Scheduled Katalon Test Suite Run
 
on:
  schedule:
    - cron: '57 7 * * *'  # Runs at 12:53 PM IST (07:23 UTC)
  workflow_dispatch:
 
jobs:
  katalon-test:
    runs-on: windows-latest
 
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
 
      # 2️⃣ Setup Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
 
      # 3️⃣ Run Katalon Test Suite
      - name: Run Scheduled Test Suite
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '10.3.2'
          projectPath: '${{ github.workspace }}'
          args: >-
            -apiKey=${{ secrets.KATALON_API_KEY }}
            -testSuitePath="Test Suites/RegisterSignIN"
            -executionProfile="default"
            -browserType="Chrome"
            -retry=0
            -noSplash
 
      # 4️⃣ Upload Katalon Reports
      - name: Upload Katalon Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-report
          path: Reports/