name: Run All Katalon Test Suites

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 mins

jobs:
  generate-matrix:
    runs-on: windows-latest
    outputs:
      suite-list: ${{ steps.extract.outputs.suites }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate suite matrix
        run: python suite-tools/generate_suite_matrix.py

      - name: Extract suite list
        id: extract
        shell: pwsh
        run: |
          $json = Get-Content suite_matrix.json -Raw
          echo "suites=$json" >> $env:GITHUB_OUTPUT

  run-suites:
    needs: generate-matrix
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJson(needs.generate-matrix.outputs.suite-list) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Test Suite
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '10.3.2'
          projectPath: '${{ github.workspace }}'
          args: >-
            -apiKey=${{ secrets.KATALON_API_KEY }}
            -testSuitePath="${{ matrix.suite }}"
            -executionProfile="default"
            -browserType="Chrome"
            -retry=0
            -noSplash

      - name: Sanitize suite name
        id: sanitize
        shell: pwsh
        run: |
          $safeName = "${{ matrix.suite }}" -replace '/', '_'
          echo "safe_name=$safeName" >> $env:GITHUB_ENV

      - name: Upload Katalon Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-report-${{ env.safe_name }}
          path: Reports/