name: Run Katalon Test Suites on Changes

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: windows-latest
    outputs:
      suite-list: ${{ steps.extract.outputs.suites }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Changed Test Suites
        id: extract
        shell: pwsh
        run: |
          git fetch --unshallow
          $changedFiles = git diff --name-only HEAD^ HEAD
          $testSuiteChanged = $changedFiles | Where-Object { $_ -like "Test Suites/*.ts" }

          $suitePaths = @()
          foreach ($suite in $testSuiteChanged) {
            $suitePaths += ($suite -replace '\\.ts$', '')
          }

          if ($suitePaths.Count -eq 0) {
            echo "suites=[]" >> $env:GITHUB_OUTPUT
          } else {
            $json = "[" + ($suitePaths | ForEach-Object { '\"' + $_ + '\"' }) -join "," + "]"
            echo "suites=$json" >> $env:GITHUB_OUTPUT
          }

  run-suites:
    needs: detect-changes
    runs-on: windows-latest
    if: needs.detect-changes.outputs.suite-list != '[]'
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJson(needs.detect-changes.outputs.suite-list) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Test Suite
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '10.3.2'
          projectPath: '${{ github.workspace }}'
          args: >-
            -apiKey=${{ secrets.KATALON_API_KEY }}
            -testSuitePath="${{ matrix.suite }}"
            -executionProfile="default"
            -browserType="Chrome"
            -retry=0
            -noSplash

      - name: Sanitize suite name
        id: sanitize
        shell: pwsh
        run: |
          $safeName = "${{ matrix.suite }}" -replace '/', '_'
          echo "safe_name=$safeName" >> $env:GITHUB_ENV

      - name: Upload Katalon Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-report-${{ env.safe_name }}
          path: Reports/